version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: node:18
    container_name: ceezer-backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: root
      DB_NAME: portfolio
      PORT: 8080
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

  frontend:
    image: node:18
    container_name: ceezer-frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d portfolio" ]
      interval: 5s
      retries: 5
      start_period: 10s
volumes:
  postgres_data: