version: '3.8'

services:
  app:
    image: node:18
    container_name: ceezer-case
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: root
      DATABASE_NAME: portfolio
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
