name: BackendCI

on:
  push:
    branches:
      - main
      - 'feature/CZR-*'
      - 'fix/CZR-*'
  pull_request:
    branches:
      - main
      - 'feature/CZR-*'
      - 'fix/CZR-*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.20.5 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Lint
        run: |
          cd backend
          npm run lint

      - name: Build
        run: |
          cd backend
          npm run build

      - name: Test
        run: |
          cd backend
          npm run test